baseURL = "https://cussoncheung.com/"
languageCode = "en-us"
title = "cussoncheung.com"
theme = "devresume-theme"


[Permalinks]
    post = "/:filename/"


[params]
    author = "Cusson Cheung"
    description = "Cusson Cheung"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"


    [params.profile]
        enable = true
        name = "Cusson Cheung"
        tagline = "Software Engineer"
        avatar = "avatar.png"


    [params.contact]
        enable = true
        location = "Vancouver"

        # [[params.contact.list]]
        # icon = "fas fa-phone-square"
        # url = "tel:#"
        # text = "0123 4567 890"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "cussonkc@gmail.com"
        # [[params.contact.list]]
        # icon = "fas fa-globe"
        # url = "#"
        # text = "www.yourwebsite.com"



    [params.summary]
        enable = true
        text = "Detailed-oriented and efficient full stack developer with 3 years of experience in Ruby on Rails, eCommerce, Javascript, etc. Seeking to help the bottom line at your business. I am dedicated to constantly improving tools and infrastructure to maximize productivity, minimizing system downtime, and quickly respond to the changing needs of the business."


    [params.education]
        enable = true
        [[params.education.list]]
        degree = "AWS Academy Cloud Architecting"
        university = "B.C.I.T."
        dates = "2020 - 2020"
        [[params.education.list]]
        degree = "Software System Developer"
        university = "B.C.I.T."
        dates = "2016 - 2017"
        [[params.education.list]]
        degree = "Technical Web Designer"
        university = "B.C.I.T."
        dates = "2015 - 2016"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/Node.js/ReactJS"
        [[params.skills.list.items]]
        details = "Ruby/Ruby On Rails/PHP"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL/Firebase"
        [[params.skills.list.items]]
        details = "Git/GitHub"
        [[params.skills.list.items]]
        details = "HTTP & REST API model knowledge"
        [[params.skills.list.items]]
        details = "Wordpress/NetlifyCMS"
        [[params.skills.list.items]]
        details = "HTML/CSS/SCSS/Bootstrap"
        [[params.skills.list.items]]
        details = "Proficient In Adobe Creative Suite"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"


    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "Cantonese"
        level = "Native"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Badminton"
        [[params.interests.list]]
        name = "Video Games"
        [[params.interests.list]]
        name = "Travelling"
        [[params.interests.list]]
        name = "Skiing"
        [[params.interests.list]]
        name = "Motorcycle"


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Associate Full Stack Web Engineer"
        dates = "2017 - Present"
        company = "iPro Group"
        details = "Responsible for the coding, innovative design and layout of websites from concept all the way to completion from the bottom up, fashioning everything from the home page to site layout and function."
        [[params.experience.list.items]]
        details = "Completed end to end Ruby on Rails web applications which processed, analyzed, and rendered data visually combined with Devise authentication solution."
        [[params.experience.list.items]]
        details = "Liaised with back end and front end developers, quality assurance testers as needed."
        [[params.experience.list.items]]
        details = "Handled time-sensitive updates, including content changes and database advances."
        [[params.experience.list.items]]
        details = "Used various ideas from distributed computing, real-time data processing, data storage to solve challenging dataset problems."
        [[params.experience.list.items]]
        details = "Modify existing softwares to correct errors, upgrade interfaces and strengthen performance."
        [[params.experience.list.items]]
        details = "Writing and maintaining extensible code in a team environment."
        [[params.experience.list.items]]
        details = "Troubleshooting and debugging with existing code base."
        [[params.experience.list.items]]
        details = "Submit documentations for formal review and release for the team."

        [[params.experience.list]]
        title = "Web Designer"
        dates = "2010 - 2017"
        company = "iPro Interactive"
        details = "Launched, maintained and improved websites on the Wordpress platform."
        [[params.experience.list.items]]
        details = "Developed websites from front to backend using PHP, Javascript, CSS, and HTML"
        [[params.experience.list.items]]
        details = "Enhanced user experience and accomplish webpage objectives by creating site structure, navigation, page optimization, and graphics integration."
        [[params.experience.list.items]]
        details = "Implemented enhancements that revamp web functionalities and responsiveness."
        [[params.experience.list.items]]
        details = "Implementing HTML email templates and newsletters for marketing campaigns."
        

        # [[params.experience.list]]
        # title = "Senior Software Developer"
        # dates = "2014 - 2016"
        # company = "Dropbox"
        # details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        # [[params.experience.list]]
        # title = "Senior Developer"
        # dates = "2013 - 2014"
        # company = "Uber"
        # details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        # [[params.experience.list]]
        # title = "Backend Developer"
        # dates = "2014 - 2016"
        # company = "Amazon"
        # details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        # [[params.experience.list]]
        # title = "Frontend Developer"
        # dates = "2013 - 2014"
        # company = "Startup"
        # details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."


    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."


    [params.accomplishments]
        enable = true

        [[params.accomplishments.list]]
        # title = "Project Lorem Ipsum"
        # meta = "Open Source"
        tagline = "Design/maintain Javascript web scraper with puppeteer that logins to Instagram and retrive influencers and followers data statistics."

        [[params.accomplishments.list]]
        # title = "Project Sed Fringilla"
        # meta = "Open Source"
        tagline = "Modernised legacy applications built on Ruby on Rails to Docker containers and deployed on AWS."

        [[params.accomplishments.list]]
        # title = "Project Praesent"
        # meta = "Open Source"
        tagline = "Implement alert system to send real-time Slack notifications when application error/failed are raised."

        [[params.accomplishments.list]]
        # title = "Project Praesent"
        # meta = "Open Source"
        tagline = "Migrated resources to AWS to consolidate company servers to save costs each month."

        [[params.accomplishments.list]]
        # title = "Project Praesent"
        # meta = "Open Source"
        tagline = "Integrated application with Twilio to send sms notification globally."

        [[params.accomplishments.list]]
        # title = "Project Praesent"
        # meta = "Open Source"
        tagline = "Established a hands on KPI monitor for iPro Group with Ruby on Rail and Grafana."
        
        [[params.accomplishments.list]]
        # title = "Project Praesent"
        # meta = "Open Source"
        tagline = "Double new user acquisition from 10-15 users to 20-25 through the implementation of A/B testing focused on online advertising and improving the company's web presence, social media, and search engine optimization."


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/imcousin"
        title = "imcousin"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/cussoncheung"
        title = "cussoncheung"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/cussoncheung"
        title = "@cussoncheung"